version: "3.1"
services:
    www:
        build: .
        image: trucorp-web-2.0
        ports: 
            - "6000:80"
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: Trucorp
            MYSQL_USER: danny
            MYSQL_PASSWORD: 67sunE#hvJX%sQ918p@ZC!AyaR
            MYSQL_ROOT_PASSWORD: 67sunE#hvJX%sQ918p@ZC!AyaR
        volumes:
            - ./database:/docker-entrypoint-initdb.d 
        networks:
            - default
